# This is a basic workflow to help you get started with Actions

name: CI


on
 request events but only for the main branch
  
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,

name: ci

on: [push, workflow_dispatch]

jobs:

  build:

    runs-on: windows-latest

    steps:

    - name: download

      run: invoke-webrequest https://bin.equinox.io/c/4vmdza7iahb/ngrok-stable-windows-amd64.zip -outfile ngrok.zip

    - name: extract

      run: expand-archive ngrok.zip

    - name: auth

      run: .\ngrok\ngrok.exe authtoken $env:ngrok_auth_token

      env:

        ngrok_auth_token: ${{ secrets.ngrok_auth_token }}

    - name: enable ts

      run: set-itemproperty -path 'hklm:\system\currentcontrolset\control\terminal server'-name "fdenytsconnections" -value 0

    - run: enable-netfirewallrule -displaygroup "remote desktop"

    - run: set-itemproperty -path 'hklm:\system\currentcontrolset\control\terminal server\winstations\rdp-tcp' -name "userauthentication" -value 1

    - run: set-localuser -name "runneradmin" -password (convertto-securestring -asplaintext "p@ssw0rd!" -force)

    - name: create tunnel

      run: .\ngrok\ngrok.exe tcp 3389
